export const ENTIRE_SCREEN_DISPLAY_SURFACE = 'monitor';
export const SCREEN_SHARE_READY_STATE = 'live';

export const ERRORS = {
  FULL_MONITOR_NOT_SHARED: 'FULL_MONITOR_NOT_SHARED',
  SCREEN_SHARE_STREAM_ENDED: 'SCREEN_SHARE_STREAM_ENDED',
  SCREEN_SHARE_FAILED: 'SCREEN_SHARE_FAILED',
  SCREEN_SHARE_DENIED: 'SCREEN_SHARE_DENIED',
  ROLLING_WINDOW_STRATEGY_LENGTH_EXCEEDED:
    'ROLLING_WINDOW_STRATEGY_LENGTH_EXCEEDED',
};

export const ERROR_MESSAGES = {
  [ERRORS.FULL_MONITOR_NOT_SHARED]:
    'Please share your entire screen, not just a window or tab',
  [ERRORS.SCREEN_SHARE_DENIED]: 'Screen share permission was denied',
  [ERRORS.SCREEN_SHARE_FAILED]: 'Screen share failed to initialize',
  [ERRORS.SCREEN_SHARE_STREAM_ENDED]: 'Screen share stream has ended',
} as const;

export const STRATEGIES = {
  RETRY_STRATEGY: 'RETRY_STRATEGY',
  ROLLING_WINDOW_STRATEGY: 'ROLLING_WINDOW_STRATEGY',
};
